asset: subtitler.zip
tap: caseyscarborough/homebrew-subtitler/Formula/subtitler.rb
template: |
  class Subtitler < Formula
    desc "$REPO_DESCRIPTION"
    homepage "$REPO_WEBSITE"
    url "$STABLE_ASSET_URL"
    sha256 "$STABLE_ASSET_SHA256"
    license "MIT"

    depends_on "openjdk@11"

    def install
      rm "bin/subtitler.bat"
      chmod 0755, "bin/subtitler"
      bin.install "bin/subtitler"
      (libexec/"lib").install Dir["lib/*"]

      bin.env_script_all_files(libexec/"bin", JAVA_HOME: Formula["openjdk@11"].opt_prefix)
    end

    test do
      assert_match "Subtitler v$STABLE_VERSION_NUMBER", shell_output("#{bin}/subtitler -v")
    end
  end
