name: Perform Release
on:
  push:
    tags:
      - '*'
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Publish Package
        run: |
          export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Publishing package version ${VERSION} for user ${GITHUB_ACTOR}..."
          ./gradlew -Pversion=${VERSION} publish
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Build CLI Zip File
        run: |
          export VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "Building distribution file for version ${VERSION}..."
          ./gradlew -Pversion=${VERSION} distZip
          mv build/distributions/subtitler-${VERSION}.zip subtitler.zip
          shasum -a 256 subtitler.zip > subtitler.zip.sha256
      - name: Generate Release Notes
        run: |
          export PREVIOUS=$(git describe --tags $(git rev-list --tags --max-count=2) --abbrev=0 | tail -n1)
          echo "Previous release was $PREVIOUS"
          git log --pretty=format:"- %s" $PREVIOUS..HEAD > release_notes.txt
          cat release_notes.txt
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          files: |
            subtitler.zip
            subtitler.zip.sha256
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          body_path: release_notes.txt
      - name: Update Homebrew Tap
        uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: subtitler
          formula-path: Formula/subtitler.rb
          homebrew-tap: caseyscarborough/homebrew-subtitler
          base-branch: master
          download-url: https://github.com/caseyscarborough/subtitler/releases/download/${{ github.event.release.tag_name }}/subtitler.zip
          commit-message: |
            {{formulaName}} {{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
